apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-role-binding
  namespace: dev
subjects:
  - kind: User
    name: "johndoe"
roleRef:
  kind: Role
  name: "admin"
  apiGroup: rbac.authorization.k8s.io
