apiVersion: v1
kind: Pod
metadata:
  name: springboot-pod
spec:
  containers:
    # APM container (Elastic APM)
    - name: apm-agent-container
      image: docker.elastic.co/apm/apm-agent-java:latest
      env:
        - name: ELASTIC_APM_SERVER_URL
          value: "http://your-apm-server:8200"
        - name: ELASTIC_APM_APPLICATION_NAME
          value: "springboot-app"
      ports:
        - containerPort: 8200  # APM server port, if needed for connection
      resources:
        limits:
          memory: "100Mi"
          cpu: "100m"
    # Spring Boot application container
    - name: springboot-container
      image: your-springboot-image:latest
      ports:
        - containerPort: 8080
      env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://your-database-url:3306/your-database
        - name: SPRING_DATASOURCE_USERNAME
          value: your-db-username
        - name: SPRING_DATASOURCE_PASSWORD
          value: your-db-password
        - name: SPRING_PROFILES_ACTIVE
          value: dev
