apiVersion: v1
kind: Pod
metadata:
  name: springboot-pod
spec:
  containers:
    - name: springboot-container
      image: your-springboot-image:latest
      ports:
        - containerPort: 8080
      env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://your-database-url:3306/your-database
        - name: SPRING_DATASOURCE_USERNAME
          value: your-db-username
        - name: SPRING_DATASOURCE_PASSWORD
          value: your-db-password
        - name: SPRING_PROFILES_ACTIVE
          value: dev
