apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp-app
spec:
  containers:
    - name: webapp-container
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
        requests:
          memory: "128Mi"
          cpu: "250m"
